# Generated by Django 5.0.2 on 2025-05-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
